version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: ari_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ariyoo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data: